In [10]:
import pandas as pd
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler

# File và tên cột
filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

# ✅ Đọc dữ liệu đúng cách, xử lý ký tự '?', và ép tất cả về số
data = pd.read_csv(filename, names=names, na_values='?')
data = data.apply(pd.to_numeric, errors='coerce')

# ✅ Tách phần input và output
array = data.values
X = array[:, 0:8]
Y = array[:, 8]

# ✅ Chuẩn hóa dữ liệu
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(X)

# ✅ In kết quả
set_printoptions(precision=3)
print(rescaledX[0:5, :])


[[  nan   nan   nan   nan   nan   nan   nan   nan]
 [0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]]
