In [3]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from numpy import set_printoptions

# File và tên cột
filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

# ✅ Đọc dữ liệu đúng cách — xử lý ký tự '?', ép kiểu về số
data = pd.read_csv(filename, names=names, na_values='?')
data = data.apply(pd.to_numeric, errors='coerce')

# ✅ Tách input (X) và output (Y)
array = data.values
X = array[:, 0:8]
Y = array[:, 8]

# ✅ Chuẩn hóa dữ liệu (trung bình = 0, độ lệch chuẩn = 1)
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)

# ✅ Hiển thị kết quả
set_printoptions(precision=3)
print(rescaledX[0:5, :])


[[   nan    nan    nan    nan    nan    nan    nan    nan]
 [ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]]
