In [2]:
import pandas as pd
from sklearn.preprocessing import Normalizer
from numpy import set_printoptions

# Đọc dữ liệu
filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

data = pd.read_csv(filename, names=names, na_values='?')
data = data.apply(pd.to_numeric, errors='coerce')

# ✅ Xóa các hàng có NaN
data = data.dropna()

# Tách X và Y
array = data.values
X = array[:, 0:8]
Y = array[:, 8]

# Normalize (chuẩn hóa độ dài vector = 1)
scaler = Normalizer().fit(X)
normalizedX = scaler.transform(X)

# Hiển thị kết quả
set_printoptions(precision=3)
print(normalizedX[0:5, :])


[[0.034 0.828 0.403 0.196 0.    0.188 0.004 0.28 ]
 [0.008 0.716 0.556 0.244 0.    0.224 0.003 0.261]
 [0.04  0.924 0.323 0.    0.    0.118 0.003 0.162]
 [0.007 0.588 0.436 0.152 0.622 0.186 0.001 0.139]
 [0.    0.596 0.174 0.152 0.731 0.188 0.01  0.144]]
