In [1]:
import pandas as pd
from sklearn.preprocessing import Binarizer
from numpy import set_printoptions

# Đọc dữ liệu và xử lý NaN
filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

# Đọc file, chuyển '?' thành NaN và ép kiểu số
data = pd.read_csv(filename, names=names, na_values='?')
data = data.apply(pd.to_numeric, errors='coerce')

# Điền giá trị trung bình thay cho NaN
data.fillna(data.mean(), inplace=True)

# Tách X và Y
array = data.values
X = array[:, 0:8]
Y = array[:, 8]

# Nhị phân hóa (threshold=0.0 → mọi giá trị >0 thành 1, <=0 thành 0)
binarizer = Binarizer(threshold=0.0).fit(X)
binaryX = binarizer.transform(X)

# In ra kết quả
set_printoptions(precision=3)
print(binaryX[0:5, :])


[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
